services:
  aura-catcher-mariadb:
    image: mariadb:latest
    container_name: aura-catcher-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - aura-catcher-mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  aura-catcher-backend:
    build:
      # backend needs the full context because it uses shared/
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: aura-catcher-backend
    environment:
      DB_HOST: aura-catcher-mariadb # Override 'localhost' 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATA_DIR: /app/data
    volumes:
      - aura-catcher-backend_data:/app/data
    depends_on:
      aura-catcher-mariadb:
        condition: service_healthy
    restart: always

  aura-catcher-frontend:
    build:
      # frontend needs the full context because it uses shared/
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: aura-catcher-frontend
    ports:
      - "8080:8080"
    depends_on:
      - aura-catcher-backend
    restart: always

volumes:
  aura-catcher-mariadb_data:
  aura-catcher-backend_data:
